apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: admin
spec:
  version: v0.1.0
  homepage: https://github.com/WhiteAnthrax/kubectl-admin
  shortDescription: "Launch a debug pod on a node and auto-cleanup after exit"
  description: |
    Starts a privileged debug pod on a specified node using `kubectl debug`,
    chroots into the host, saves the debug session log under ~/logs/kubectl-admin/,
    and deletes the debug pod automatically after exiting.
    Automatically selects a supported --profile based on kubectl version.

  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values: ["linux"]
    uri: https://github.com/WhiteAnthrax/kubectl-admin/releases/download/v1.2/kubectl-admin.tar.gz
    sha256: 743ac27617a3b18f065f97889ddc518e3ceb99f99cb67d6f869259e51d9ab29a
    bin: kubectl-admin
